mysql
mysql-server
qpid-cpp-server
openstack-keystone
openstack-glance
openstack-nova-api
openstack-nova-cert
openstack-nova-conductor
openstack-nova-console
openstack-nova-novncproxy
openstack-nova-scheduler
openstack-cinder
memcached
python-memcached
mod_wsgi
openstack-dashboard
openstack-swift-proxy
#openstack-neutron
