uln-internal-setup
kmod-openvswitch
libvirt-daemon-xen
openstack-release
openstack-utils
openstack-selinux
MySQL-python
python-ceilometerclient
python-cinderclient
python-glanceclient
python-heatclient
python-keystoneclient
python-neutronclient
python-novaclient
python-swiftclient
python-troveclient
openstack-nova-compute
xinetd
openstack-swift-account
openstack-swift-container
openstack-swift-object
xfsprogs
#openstack-neutron-ml2
#openstack-neutron-openvswitch
-ovs-agent
-devmon
-ovmwatch
-ovs-release
-ovs-utils
-ovs-config
-ovm-consoled
